# Site settings
title: Devons Blog
email: devonsmith34084@gmail.com
description: "i will blog about things here"
baseurl: ""
url: "http://devonsmith34084.github.io"

# Build settings
markdown: kramdown
permalink: pretty
